site_name: Hacman - Shapeoko 2
site_url: http://hacmanchester.github.io/Tools.Shapeoko2/
repo_url: https://github.com/HACManchester/Tools.Shapeoko2/
site_description: Hacman - Shapeoko 2
edit_uri: edit/master/MkDocs/Docs

pages:
- Home: index.md
- FreeCAD:
    - File Importing: FreeCad/File-Import.md
    - Exporting GCode: FreeCad/Export-GCode.md
- Hsmworks:
    - Adaptive Clearing: Hsmworks/AdaptClear.md
    - Simulation: Hsmworks/Simulation.md
- Milling:
    - Connecting - USB: Milling/Connecting.md
    - Jogging / Moving the CNC: Milling/Jog.md
    - Loading and Setup: Milling/Loading-Setup.md
    - Simulation: Milling/Simulation.md
    - Milling Material: Milling/Material.md
    - Feed Rates: Milling/FeedRates.md
    - Milling: Milling/Milling.md
- Maintenance:
    - Device Overview: Maintenance/Device-Overview.md
    - Updating the Firmware: Maintenance/Updating-Firmware.md
    - Grbl Settings: Maintenance/Grbl-Settings.md
    - Todo: Maintenance/Todo.md

theme: cosmo
#theme: alabaster
#theme: readthedocs
#theme: mkdocs

# Overrides content within the selected theme
theme_dir: theme

markdown_extensions:
    - smarty

extra_css:
    - css/highlight-fix.css
    - css/highlight-custom.css
    - css/navbarfix.css
